# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/faranaiki/Git/kampwng

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/faranaiki/Git/kampwng

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/faranaiki/Git/kampwng/CMakeFiles /home/faranaiki/Git/kampwng//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/faranaiki/Git/kampwng/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named vt_gen

# Build rule for target.
vt_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vt_gen
.PHONY : vt_gen

# fast build rule for target.
vt_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vt_gen.dir/build.make CMakeFiles/vt_gen.dir/build
.PHONY : vt_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named target_parser_gen

# Build rule for target.
target_parser_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 target_parser_gen
.PHONY : target_parser_gen

# fast build rule for target.
target_parser_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_parser_gen.dir/build.make CMakeFiles/target_parser_gen.dir/build
.PHONY : target_parser_gen/fast

#=============================================================================
# Target rules for targets named kampwng

# Build rule for target.
kampwng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kampwng
.PHONY : kampwng

# fast build rule for target.
kampwng/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/build
.PHONY : kampwng/fast

src/codegen.o: src/codegen.c.o
.PHONY : src/codegen.o

# target to build an object file
src/codegen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/codegen.c.o
.PHONY : src/codegen.c.o

src/codegen.i: src/codegen.c.i
.PHONY : src/codegen.i

# target to preprocess a source file
src/codegen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/codegen.c.i
.PHONY : src/codegen.c.i

src/codegen.s: src/codegen.c.s
.PHONY : src/codegen.s

# target to generate assembly for a file
src/codegen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/codegen.c.s
.PHONY : src/codegen.c.s

src/kampwng.o: src/kampwng.c.o
.PHONY : src/kampwng.o

# target to build an object file
src/kampwng.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/kampwng.c.o
.PHONY : src/kampwng.c.o

src/kampwng.i: src/kampwng.c.i
.PHONY : src/kampwng.i

# target to preprocess a source file
src/kampwng.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/kampwng.c.i
.PHONY : src/kampwng.c.i

src/kampwng.s: src/kampwng.c.s
.PHONY : src/kampwng.s

# target to generate assembly for a file
src/kampwng.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/kampwng.c.s
.PHONY : src/kampwng.c.s

src/lexer.o: src/lexer.c.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/lexer.c.o
.PHONY : src/lexer.c.o

src/lexer.i: src/lexer.c.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/lexer.c.i
.PHONY : src/lexer.c.i

src/lexer.s: src/lexer.c.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/lexer.c.s
.PHONY : src/lexer.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kampwng.dir/build.make CMakeFiles/kampwng.dir/src/parser.c.s
.PHONY : src/parser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... target_parser_gen"
	@echo "... vt_gen"
	@echo "... kampwng"
	@echo "... src/codegen.o"
	@echo "... src/codegen.i"
	@echo "... src/codegen.s"
	@echo "... src/kampwng.o"
	@echo "... src/kampwng.i"
	@echo "... src/kampwng.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

